### ISSUE TITLE
Supporting rancher server and agents 

### ISSUE THREAD

**Issue by lavvy** [luxas/kubernetes-on-arm#32]
Hey,  just thinking if you could support rancher server and agent on arm. 
Rancher has the ability to deploy and manage many other platforms like kubernates,  hadoop etc very smoothly through their community supported catalog.  
I know Rancheros support is your roadmap,  but just thinking if the server and agents should be ported to arch or hypriotos,  it could save a whole lot

**Comment by luxas** [comment]
Hello @lavvy

I'm sorry to say, but RancherOS is far away from ARM at the moment. There is just so many things that have to be done, and we must have the full attention of the core maintainers for this to work.

Rancher is built in Java and Python, which both may run smoothly on ARM AFAIK.
But I don't have time to investigate that, I will try merge this work with mainline Kubernetes, which I guess is going to be quite hard

Even if we got Rancher up and running, no addons would be present in the community catalog, because it's ARM :/

Personally, I think Kubernetes (and that means this project) more powerful than Rancher, so this time I would advise you to:
 - A: Learn Kubernetes in-and-out and go with that, directly on ARM (the easy one)
 - B: Run Rancher with Kubernetes on top on `amd64` hosts, learn how it should work, and try to convert Rancher to ARM and use my Kubernetes binaries on top (the very hard one)

If you want to go with B, here is two images for ARM you might be interested in:
https://github.com/hypriot/rpi-java
https://github.com/hypriot/rpi-python

Hope it helps!
