### ISSUE TITLE
docker-on-arm.md missing, broken link in readme.md

### ISSUE THREAD

**Issue by v1k0d3n** [luxas/kubernetes-on-arm#85]
hey @luxas, it looks like the https://github.com/luxas/kubernetes-on-arm/blob/master/docs/docker-on-arm.md is missing. not that there isn't other information out there, but i just wanted to let you know in case there was any specific information that could help out new users using your repo. keep up the great work, man!

**Comment by luxas** [comment]
Hi @v1k0d3n! I'm glad you're still following my project so you're able to create issues :)'
I deleted the file because if I would keep it, it would be misleading because so much things have happened since I wrote it.
I hadn't time to rewrite the doc when I made the release, but maybe I'll write up something for the next release :)

**Comment by madmas** [comment]
Hi,
I started a new document :-) hope you find this useful

**Comment by luxas** [comment]
Fixed at `dev` with #97
